#![no_std]
#![deny(unsafe_code)]

//! Allocation-free input-method core for Bndroid's trusted software-keyboard
//! overlay.
//!
//! The first slice deliberately exposes only three fixed keys. While visible,
//! the complete overlay consumes pointer input so gaps between keys cannot
//! click through into an untrusted client. A contact that begins on a key is
//! captured through release, including when the pointer leaves the overlay.

use bndr_ui::{InputSample, SHELL_HEIGHT, SHELL_WIDTH, ShellRect};

mod protocol;
mod restart;
mod router;
mod service_recovery;

pub use protocol::*;
pub use restart::*;
pub use router::*;
pub use service_recovery::*;

/// Bounds owned by the trusted input overlay while it is visible.
pub const TRUSTED_OVERLAY_RECT: ShellRect = ShellRect::new(56, 336, 208, 96);
/// Fixed hit target for the Latin `A` key.
pub const A_KEY_RECT: ShellRect = ShellRect::new(64, 344, 48, 64);
/// Fixed hit target for Backspace.
pub const BACKSPACE_KEY_RECT: ShellRect = ShellRect::new(120, 344, 64, 64);
/// Fixed hit target for Enter.
pub const ENTER_KEY_RECT: ShellRect = ShellRect::new(192, 344, 64, 64);

#[cfg(not(feature = "mobile-ui-runtime"))]
const _: () = assert!(SHELL_WIDTH == 320);
#[cfg(not(feature = "mobile-ui-runtime"))]
const _: () = assert!(SHELL_HEIGHT == 480);
#[cfg(feature = "mobile-ui-runtime")]
const _: () = assert!(SHELL_WIDTH == 720);
#[cfg(feature = "mobile-ui-runtime")]
const _: () = assert!(SHELL_HEIGHT == 1_600);
const _: () = assert!(TRUSTED_OVERLAY_RECT.x + TRUSTED_OVERLAY_RECT.width <= SHELL_WIDTH);
const _: () = assert!(TRUSTED_OVERLAY_RECT.y + TRUSTED_OVERLAY_RECT.height <= SHELL_HEIGHT);
const _: () = assert!(A_KEY_RECT.x >= TRUSTED_OVERLAY_RECT.x);
const _: () = assert!(BACKSPACE_KEY_RECT.x >= TRUSTED_OVERLAY_RECT.x);
const _: () = assert!(ENTER_KEY_RECT.x >= TRUSTED_OVERLAY_RECT.x);
const _: () =
    assert!(A_KEY_RECT.x + A_KEY_RECT.width <= TRUSTED_OVERLAY_RECT.x + TRUSTED_OVERLAY_RECT.width);
const _: () = assert!(
    BACKSPACE_KEY_RECT.x + BACKSPACE_KEY_RECT.width
        <= TRUSTED_OVERLAY_RECT.x + TRUSTED_OVERLAY_RECT.width
);
const _: () = assert!(
    ENTER_KEY_RECT.x + ENTER_KEY_RECT.width <= TRUSTED_OVERLAY_RECT.x + TRUSTED_OVERLAY_RECT.width
);
const _: () = assert!(A_KEY_RECT.y >= TRUSTED_OVERLAY_RECT.y);
const _: () = assert!(
    A_KEY_RECT.y + A_KEY_RECT.height <= TRUSTED_OVERLAY_RECT.y + TRUSTED_OVERLAY_RECT.height
);
const _: () = assert!(A_KEY_RECT.x + A_KEY_RECT.width <= BACKSPACE_KEY_RECT.x);
const _: () = assert!(BACKSPACE_KEY_RECT.x + BACKSPACE_KEY_RECT.width <= ENTER_KEY_RECT.x);

/// One key in the fixed trusted overlay.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SoftKey {
    A,
    Backspace,
    Enter,
}

/// Returns the fixed key containing `(x, y)` using half-open rectangles.
pub const fn key_at(x: u16, y: u16) -> Option<SoftKey> {
    if A_KEY_RECT.contains(x, y) {
        Some(SoftKey::A)
    } else if BACKSPACE_KEY_RECT.contains(x, y) {
        Some(SoftKey::Backspace)
    } else if ENTER_KEY_RECT.contains(x, y) {
        Some(SoftKey::Enter)
    } else {
        None
    }
}

/// A semantic action produced by one completed key activation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputAction {
    Preedit(char),
    Commit(&'static str),
    DeleteSurrounding {
        before_scalars: u8,
        after_scalars: u8,
    },
}

/// Routing result for one pointer report.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InputOutcome {
    /// Whether the trusted overlay owns this report and the caller must not
    /// route it to an application.
    pub consumed: bool,
    /// At most one text action generated by this report.
    pub action: Option<InputAction>,
}

impl InputOutcome {
    pub const IGNORED: Self = Self {
        consumed: false,
        action: None,
    };

    pub const fn consumed(self) -> bool {
        self.consumed
    }

    pub const fn action(self) -> Option<InputAction> {
        self.action
    }
}

/// Saturating diagnostic counters. An activation is a press/release pair on
/// the same key, including a state-gated key whose semantic action is `None`.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct InputStatistics {
    pub contacts: u64,
    pub activations: u64,
    pub cancels: u64,
    pub hidden_drops: u64,
}

/// State for the bounded three-key input method.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InputMethodEngine {
    visible: bool,
    capture: Option<SoftKey>,
    preedit: Option<char>,
    last_sequence: u64,
    statistics: InputStatistics,
}

impl InputMethodEngine {
    /// Creates a hidden engine with no preedit or active contact.
    pub const fn new() -> Self {
        Self {
            visible: false,
            capture: None,
            preedit: None,
            last_sequence: 0,
            statistics: InputStatistics {
                contacts: 0,
                activations: 0,
                cancels: 0,
                hidden_drops: 0,
            },
        }
    }

    pub const fn is_visible(&self) -> bool {
        self.visible
    }

    pub const fn captured_key(&self) -> Option<SoftKey> {
        self.capture
    }

    pub const fn preedit(&self) -> Option<char> {
        self.preedit
    }

    pub const fn last_sequence(&self) -> u64 {
        self.last_sequence
    }

    pub const fn statistics(&self) -> InputStatistics {
        self.statistics
    }

    /// Shows the overlay. This is idempotent.
    pub const fn show(&mut self) {
        self.visible = true;
    }

    /// Hides the overlay and clears its transient text and pointer state.
    /// Hiding an active contact records one cancellation.
    pub fn hide(&mut self) {
        self.visible = false;
        if self.capture.take().is_some() {
            self.statistics.cancels = self.statistics.cancels.saturating_add(1);
        }
        self.preedit = None;
    }

    /// Cancels an active pointer contact without changing preedit state.
    pub fn cancel_contact(&mut self) -> bool {
        if self.capture.take().is_none() {
            return false;
        }
        self.statistics.cancels = self.statistics.cancels.saturating_add(1);
        true
    }

    /// Handles one normalized pointer report.
    ///
    /// Sequences must increase strictly. A stale/replayed report never changes
    /// engine state, but it is still consumed when it targets the visible
    /// trusted overlay or an active capture.
    pub fn handle(&mut self, sample: InputSample) -> InputOutcome {
        let owns_report = self.visible
            && (self.capture.is_some() || TRUSTED_OVERLAY_RECT.contains(sample.x(), sample.y()));

        if !self.visible {
            self.statistics.hidden_drops = self.statistics.hidden_drops.saturating_add(1);
            if sample.sequence() > self.last_sequence {
                self.last_sequence = sample.sequence();
            }
            return InputOutcome::IGNORED;
        }

        if sample.sequence() <= self.last_sequence {
            return InputOutcome {
                consumed: owns_report,
                action: None,
            };
        }
        self.last_sequence = sample.sequence();

        if let Some(captured) = self.capture {
            if sample.pressed() {
                return InputOutcome {
                    consumed: true,
                    action: None,
                };
            }

            self.capture = None;
            if key_at(sample.x(), sample.y()) != Some(captured) {
                self.statistics.cancels = self.statistics.cancels.saturating_add(1);
                return InputOutcome {
                    consumed: true,
                    action: None,
                };
            }

            self.statistics.activations = self.statistics.activations.saturating_add(1);
            return InputOutcome {
                consumed: true,
                action: self.activate(captured),
            };
        }

        if sample.pressed()
            && let Some(key) = key_at(sample.x(), sample.y())
        {
            self.capture = Some(key);
            self.statistics.contacts = self.statistics.contacts.saturating_add(1);
        }

        InputOutcome {
            consumed: TRUSTED_OVERLAY_RECT.contains(sample.x(), sample.y()),
            action: None,
        }
    }

    fn activate(&mut self, key: SoftKey) -> Option<InputAction> {
        match key {
            SoftKey::A => {
                self.preedit = Some('a');
                Some(InputAction::Preedit('a'))
            }
            SoftKey::Enter if self.preedit.is_some() => {
                self.preedit = None;
                Some(InputAction::Commit("a"))
            }
            SoftKey::Backspace if self.preedit.is_none() => Some(InputAction::DeleteSurrounding {
                before_scalars: 1,
                after_scalars: 0,
            }),
            SoftKey::Backspace | SoftKey::Enter => None,
        }
    }
}

impl Default for InputMethodEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(sequence: u64, x: u16, y: u16, pressed: bool) -> InputSample {
        InputSample::try_new(sequence, x, y, pressed).unwrap()
    }

    fn point(rect: ShellRect) -> (u16, u16) {
        (rect.x + rect.width / 2, rect.y + rect.height / 2)
    }

    fn tap(engine: &mut InputMethodEngine, sequence: &mut u64, rect: ShellRect) -> InputOutcome {
        let (x, y) = point(rect);
        *sequence += 1;
        let down = engine.handle(sample(*sequence, x, y, true));
        assert_eq!(
            down,
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        *sequence += 1;
        engine.handle(sample(*sequence, x, y, false))
    }

    #[test]
    fn fixed_layout_is_inside_trusted_overlay_and_disjoint() {
        for rect in [A_KEY_RECT, BACKSPACE_KEY_RECT, ENTER_KEY_RECT] {
            assert!(TRUSTED_OVERLAY_RECT.contains(rect.x, rect.y));
            assert!(
                TRUSTED_OVERLAY_RECT.contains(rect.x + rect.width - 1, rect.y + rect.height - 1)
            );
        }
        assert_eq!(key_at(116, 360), None);
        assert_eq!(key_at(188, 360), None);
    }

    #[test]
    fn key_rectangles_use_half_open_boundaries() {
        assert_eq!(key_at(A_KEY_RECT.x, A_KEY_RECT.y), Some(SoftKey::A));
        assert_eq!(
            key_at(A_KEY_RECT.x + A_KEY_RECT.width - 1, A_KEY_RECT.y),
            Some(SoftKey::A)
        );
        assert_eq!(
            key_at(A_KEY_RECT.x, A_KEY_RECT.y + A_KEY_RECT.height - 1),
            Some(SoftKey::A)
        );
        assert_eq!(key_at(A_KEY_RECT.x + A_KEY_RECT.width, A_KEY_RECT.y), None);
        assert_eq!(key_at(A_KEY_RECT.x, A_KEY_RECT.y + A_KEY_RECT.height), None);
    }

    #[test]
    fn all_key_targets_include_their_last_pixel() {
        assert_eq!(
            key_at(
                BACKSPACE_KEY_RECT.x + BACKSPACE_KEY_RECT.width - 1,
                BACKSPACE_KEY_RECT.y + BACKSPACE_KEY_RECT.height - 1
            ),
            Some(SoftKey::Backspace)
        );
        assert_eq!(
            key_at(
                ENTER_KEY_RECT.x + ENTER_KEY_RECT.width - 1,
                ENTER_KEY_RECT.y + ENTER_KEY_RECT.height - 1
            ),
            Some(SoftKey::Enter)
        );
    }

    #[test]
    fn hidden_input_is_never_consumed_and_is_counted() {
        let mut engine = InputMethodEngine::new();
        let (x, y) = point(A_KEY_RECT);
        assert_eq!(engine.handle(sample(1, x, y, true)), InputOutcome::IGNORED);
        assert_eq!(engine.handle(sample(2, x, y, false)), InputOutcome::IGNORED);
        assert_eq!(engine.statistics().hidden_drops, 2);
        assert_eq!(engine.statistics().contacts, 0);
        assert_eq!(engine.last_sequence(), 2);
    }

    #[test]
    fn visible_overlay_gaps_are_consumed_without_starting_contact() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let outcome = engine.handle(sample(1, 116, 360, true));
        assert_eq!(
            outcome,
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.captured_key(), None);
        assert_eq!(engine.statistics(), InputStatistics::default());
    }

    #[test]
    fn a_press_release_produces_preedit() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        assert_eq!(
            tap(&mut engine, &mut sequence, A_KEY_RECT).action,
            Some(InputAction::Preedit('a'))
        );
        assert_eq!(engine.preedit(), Some('a'));
        assert_eq!(
            engine.statistics(),
            InputStatistics {
                contacts: 1,
                activations: 1,
                cancels: 0,
                hidden_drops: 0,
            }
        );
    }

    #[test]
    fn enter_without_preedit_is_a_gated_activation() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        assert_eq!(tap(&mut engine, &mut sequence, ENTER_KEY_RECT).action, None);
        assert_eq!(engine.preedit(), None);
        assert_eq!(engine.statistics().activations, 1);
    }

    #[test]
    fn enter_commits_a_and_clears_preedit() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        tap(&mut engine, &mut sequence, A_KEY_RECT);
        assert_eq!(
            tap(&mut engine, &mut sequence, ENTER_KEY_RECT).action,
            Some(InputAction::Commit("a"))
        );
        assert_eq!(engine.preedit(), None);
    }

    #[test]
    fn backspace_without_preedit_deletes_one_scalar_before_cursor() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        assert_eq!(
            tap(&mut engine, &mut sequence, BACKSPACE_KEY_RECT).action,
            Some(InputAction::DeleteSurrounding {
                before_scalars: 1,
                after_scalars: 0,
            })
        );
    }

    #[test]
    fn backspace_with_preedit_is_gated_and_preserves_preedit() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        tap(&mut engine, &mut sequence, A_KEY_RECT);
        assert_eq!(
            tap(&mut engine, &mut sequence, BACKSPACE_KEY_RECT).action,
            None
        );
        assert_eq!(engine.preedit(), Some('a'));
    }

    #[test]
    fn release_outside_cancels_captured_contact_without_action() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let (x, y) = point(A_KEY_RECT);
        engine.handle(sample(1, x, y, true));
        let outcome = engine.handle(sample(2, 0, 0, false));
        assert_eq!(
            outcome,
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.captured_key(), None);
        assert_eq!(engine.preedit(), None);
        assert_eq!(engine.statistics().cancels, 1);
        assert_eq!(engine.statistics().activations, 0);
    }

    #[test]
    fn release_on_different_key_cancels_without_action() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let (ax, ay) = point(A_KEY_RECT);
        let (ex, ey) = point(ENTER_KEY_RECT);
        engine.handle(sample(1, ax, ay, true));
        let outcome = engine.handle(sample(2, ex, ey, false));
        assert_eq!(outcome.action, None);
        assert!(outcome.consumed);
        assert_eq!(engine.statistics().cancels, 1);
    }

    #[test]
    fn active_capture_consumes_pressed_motion_outside_overlay() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let (x, y) = point(A_KEY_RECT);
        engine.handle(sample(1, x, y, true));
        assert_eq!(
            engine.handle(sample(2, 0, 0, true)),
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.captured_key(), Some(SoftKey::A));
        assert_eq!(engine.statistics().contacts, 1);
    }

    #[test]
    fn stale_sequence_does_not_release_capture_or_mutate_counters() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let (x, y) = point(A_KEY_RECT);
        engine.handle(sample(2, x, y, true));
        let before = engine.statistics();
        assert_eq!(
            engine.handle(sample(1, x, y, false)),
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.captured_key(), Some(SoftKey::A));
        assert_eq!(engine.statistics(), before);
        assert_eq!(
            engine.handle(sample(3, x, y, false)).action,
            Some(InputAction::Preedit('a'))
        );
    }

    #[test]
    fn orphan_release_does_not_create_activation_or_cancel() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let (x, y) = point(A_KEY_RECT);
        assert_eq!(
            engine.handle(sample(1, x, y, false)),
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.statistics(), InputStatistics::default());
    }

    #[test]
    fn hide_cancels_contact_and_clears_preedit() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        tap(&mut engine, &mut sequence, A_KEY_RECT);
        let (x, y) = point(ENTER_KEY_RECT);
        sequence += 1;
        engine.handle(sample(sequence, x, y, true));
        engine.hide();
        assert!(!engine.is_visible());
        assert_eq!(engine.captured_key(), None);
        assert_eq!(engine.preedit(), None);
        assert_eq!(engine.statistics().cancels, 1);
        sequence += 1;
        assert_eq!(
            engine.handle(sample(sequence, x, y, false)),
            InputOutcome::IGNORED
        );
        assert_eq!(engine.statistics().hidden_drops, 1);
    }

    #[test]
    fn explicit_cancel_preserves_preedit() {
        let mut engine = InputMethodEngine::new();
        engine.show();
        let mut sequence = 0;
        tap(&mut engine, &mut sequence, A_KEY_RECT);
        let (x, y) = point(ENTER_KEY_RECT);
        sequence += 1;
        engine.handle(sample(sequence, x, y, true));
        assert!(engine.cancel_contact());
        assert!(!engine.cancel_contact());
        assert_eq!(engine.preedit(), Some('a'));
        assert_eq!(engine.statistics().cancels, 1);
    }

    #[test]
    fn hidden_sequences_advance_replay_floor_across_show() {
        let mut engine = InputMethodEngine::new();
        let (x, y) = point(A_KEY_RECT);
        engine.handle(sample(10, x, y, true));
        engine.show();
        assert_eq!(
            engine.handle(sample(9, x, y, true)),
            InputOutcome {
                consumed: true,
                action: None
            }
        );
        assert_eq!(engine.captured_key(), None);
        assert_eq!(engine.last_sequence(), 10);
    }

    #[test]
    fn statistics_saturate_instead_of_wrapping() {
        let mut engine = InputMethodEngine::new();
        engine.statistics = InputStatistics {
            contacts: u64::MAX,
            activations: u64::MAX,
            cancels: u64::MAX,
            hidden_drops: u64::MAX,
        };
        let (x, y) = point(A_KEY_RECT);
        engine.handle(sample(1, x, y, false));
        assert_eq!(engine.statistics().hidden_drops, u64::MAX);
        engine.show();
        engine.handle(sample(2, x, y, true));
        engine.handle(sample(3, x, y, false));
        assert_eq!(engine.statistics().contacts, u64::MAX);
        assert_eq!(engine.statistics().activations, u64::MAX);
    }
}
