// Rasterized, subsetted font data derived from Fira Sans.
// This modified font data is licensed under the SIL Open Font License 1.1.
// It is named Bndroid Sans Raster; the reserved font name is not used.
// See LICENSES/OFL-1.1-Bndroid-Sans-Raster.txt.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct RasterGlyph {
    pub data_offset: u32,
    pub x_offset: i8,
    pub y_offset: i8,
    pub width: u8,
    pub height: u8,
    pub advance: u8,
}

pub(super) const FONT_ALPHA4_BYTES: usize = 126023;

pub(super) const LABEL_LINE_HEIGHT: u8 = 32;
pub(super) const LABEL_GLYPHS: [RasterGlyph; 95] = [
    RasterGlyph {
        data_offset: 0,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 0,
        x_offset: -1,
        y_offset: 5,
        width: 7,
        height: 20,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 70,
        x_offset: -1,
        y_offset: 5,
        width: 11,
        height: 19,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 175,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 318,
        x_offset: -1,
        y_offset: 2,
        width: 15,
        height: 26,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 513,
        x_offset: -1,
        y_offset: 4,
        width: 22,
        height: 21,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 744,
        x_offset: -1,
        y_offset: 5,
        width: 20,
        height: 20,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 944,
        x_offset: -1,
        y_offset: 5,
        width: 7,
        height: 19,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 1011,
        x_offset: -1,
        y_offset: 1,
        width: 10,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 1146,
        x_offset: -1,
        y_offset: 1,
        width: 10,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 1281,
        x_offset: -1,
        y_offset: 4,
        width: 13,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 1411,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 1516,
        x_offset: -1,
        y_offset: 18,
        width: 7,
        height: 11,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 1555,
        x_offset: -1,
        y_offset: 13,
        width: 11,
        height: 11,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 1616,
        x_offset: -1,
        y_offset: 18,
        width: 7,
        height: 7,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 1641,
        x_offset: -1,
        y_offset: 2,
        width: 13,
        height: 25,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 1804,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 1954,
        x_offset: -1,
        y_offset: 5,
        width: 11,
        height: 19,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 2059,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 2192,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 20,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 2332,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 2475,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 20,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 2615,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 2765,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 2895,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 3045,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 3195,
        x_offset: -1,
        y_offset: 9,
        width: 7,
        height: 16,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 3251,
        x_offset: -1,
        y_offset: 9,
        width: 7,
        height: 20,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 3321,
        x_offset: -1,
        y_offset: 8,
        width: 14,
        height: 16,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 3433,
        x_offset: -1,
        y_offset: 10,
        width: 13,
        height: 14,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 3524,
        x_offset: -1,
        y_offset: 8,
        width: 14,
        height: 16,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 3636,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 3766,
        x_offset: -1,
        y_offset: 5,
        width: 26,
        height: 25,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 4091,
        x_offset: -2,
        y_offset: 5,
        width: 18,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 4262,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 4414,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 20,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 4574,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 4736,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 4869,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 5002,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 20,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 5172,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 5334,
        x_offset: -1,
        y_offset: 5,
        width: 8,
        height: 19,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 5410,
        x_offset: -2,
        y_offset: 5,
        width: 9,
        height: 23,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 5514,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 5676,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 5809,
        x_offset: -1,
        y_offset: 5,
        width: 20,
        height: 19,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 5999,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 6161,
        x_offset: -1,
        y_offset: 5,
        width: 18,
        height: 20,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 6341,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 6493,
        x_offset: -1,
        y_offset: 5,
        width: 19,
        height: 23,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 6712,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 6874,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 7024,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 7167,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 20,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 7337,
        x_offset: -2,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 7499,
        x_offset: -1,
        y_offset: 5,
        width: 22,
        height: 19,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 7708,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 7860,
        x_offset: -2,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 8022,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 8155,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 25,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 8268,
        x_offset: -1,
        y_offset: 2,
        width: 13,
        height: 25,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 8431,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 25,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 8544,
        x_offset: -1,
        y_offset: 1,
        width: 15,
        height: 23,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 8717,
        x_offset: -1,
        y_offset: 22,
        width: 15,
        height: 6,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 8762,
        x_offset: -1,
        y_offset: 2,
        width: 10,
        height: 22,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 8872,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 17,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 9000,
        x_offset: -1,
        y_offset: 3,
        width: 16,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 9176,
        x_offset: -1,
        y_offset: 8,
        width: 14,
        height: 17,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 9295,
        x_offset: -1,
        y_offset: 3,
        width: 15,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 9460,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 17,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 9588,
        x_offset: -1,
        y_offset: 3,
        width: 12,
        height: 21,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 9714,
        x_offset: -1,
        y_offset: 7,
        width: 15,
        height: 23,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 9887,
        x_offset: -1,
        y_offset: 3,
        width: 15,
        height: 21,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 10045,
        x_offset: -1,
        y_offset: 2,
        width: 8,
        height: 22,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 10133,
        x_offset: -2,
        y_offset: 2,
        width: 9,
        height: 28,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 10259,
        x_offset: -1,
        y_offset: 3,
        width: 15,
        height: 21,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 10417,
        x_offset: -1,
        y_offset: 3,
        width: 9,
        height: 22,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 10516,
        x_offset: -1,
        y_offset: 8,
        width: 21,
        height: 16,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 10684,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 16,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 10804,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 17,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 10932,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 11108,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 11273,
        x_offset: -1,
        y_offset: 8,
        width: 12,
        height: 16,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 11369,
        x_offset: -1,
        y_offset: 8,
        width: 13,
        height: 17,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 11480,
        x_offset: -1,
        y_offset: 6,
        width: 12,
        height: 19,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 11594,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 16,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 11706,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 11819,
        x_offset: -1,
        y_offset: 9,
        width: 20,
        height: 15,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 11969,
        x_offset: -2,
        y_offset: 9,
        width: 16,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 12089,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 21,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 12247,
        x_offset: -1,
        y_offset: 9,
        width: 13,
        height: 15,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 12345,
        x_offset: -1,
        y_offset: 1,
        width: 9,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 12467,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 25,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 12580,
        x_offset: -1,
        y_offset: 1,
        width: 10,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 12715,
        x_offset: -1,
        y_offset: 12,
        width: 14,
        height: 12,
        advance: 13,
    },
];

pub(super) const LABEL_MAP: [u8; 95] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
];

pub(super) const CAPTION_LINE_HEIGHT: u8 = 32;
pub(super) const CAPTION_GLYPHS: [RasterGlyph; 95] = [
    RasterGlyph {
        data_offset: 12799,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 12799,
        x_offset: -1,
        y_offset: 5,
        width: 7,
        height: 20,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 12869,
        x_offset: -1,
        y_offset: 5,
        width: 11,
        height: 19,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 12974,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 13117,
        x_offset: -1,
        y_offset: 2,
        width: 14,
        height: 26,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 13299,
        x_offset: -1,
        y_offset: 4,
        width: 21,
        height: 21,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 13520,
        x_offset: -1,
        y_offset: 5,
        width: 19,
        height: 20,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 13710,
        x_offset: -1,
        y_offset: 5,
        width: 6,
        height: 19,
        advance: 6,
    },
    RasterGlyph {
        data_offset: 13767,
        x_offset: -1,
        y_offset: 1,
        width: 9,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 13889,
        x_offset: -1,
        y_offset: 1,
        width: 9,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 14011,
        x_offset: -1,
        y_offset: 4,
        width: 13,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 14141,
        x_offset: -1,
        y_offset: 9,
        width: 13,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 14239,
        x_offset: -1,
        y_offset: 18,
        width: 7,
        height: 10,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 14274,
        x_offset: -1,
        y_offset: 13,
        width: 11,
        height: 11,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 14335,
        x_offset: -1,
        y_offset: 18,
        width: 7,
        height: 7,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 14360,
        x_offset: -1,
        y_offset: 2,
        width: 12,
        height: 25,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 14510,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 14660,
        x_offset: -1,
        y_offset: 5,
        width: 10,
        height: 19,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 14755,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 14879,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 20,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 15009,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 15152,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 20,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 15282,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 15422,
        x_offset: -1,
        y_offset: 5,
        width: 12,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 15542,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 15692,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 15832,
        x_offset: -1,
        y_offset: 10,
        width: 7,
        height: 15,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 15885,
        x_offset: -1,
        y_offset: 10,
        width: 7,
        height: 18,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 15948,
        x_offset: -1,
        y_offset: 8,
        width: 13,
        height: 16,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 16052,
        x_offset: -1,
        y_offset: 10,
        width: 13,
        height: 14,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 16143,
        x_offset: -1,
        y_offset: 8,
        width: 13,
        height: 16,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 16247,
        x_offset: -1,
        y_offset: 5,
        width: 13,
        height: 20,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 16377,
        x_offset: -1,
        y_offset: 5,
        width: 25,
        height: 25,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 16690,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 16842,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 16994,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 17144,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 17306,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 17439,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 17572,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 20,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 17732,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 17884,
        x_offset: -1,
        y_offset: 5,
        width: 7,
        height: 19,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 17951,
        x_offset: -1,
        y_offset: 5,
        width: 8,
        height: 23,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 18043,
        x_offset: -1,
        y_offset: 5,
        width: 17,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 18205,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 18338,
        x_offset: -1,
        y_offset: 5,
        width: 20,
        height: 19,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 18528,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 18680,
        x_offset: -1,
        y_offset: 5,
        width: 18,
        height: 20,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 18860,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 19012,
        x_offset: -1,
        y_offset: 5,
        width: 18,
        height: 22,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 19210,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 19362,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 20,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 19512,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 19655,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 20,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 19815,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 19967,
        x_offset: -1,
        y_offset: 5,
        width: 22,
        height: 19,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 20176,
        x_offset: -1,
        y_offset: 5,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 20319,
        x_offset: -1,
        y_offset: 5,
        width: 16,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 20471,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 20604,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 25,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 20717,
        x_offset: -1,
        y_offset: 2,
        width: 12,
        height: 25,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 20867,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 25,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 20980,
        x_offset: -1,
        y_offset: 1,
        width: 14,
        height: 23,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 21141,
        x_offset: -1,
        y_offset: 22,
        width: 15,
        height: 6,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 21186,
        x_offset: -1,
        y_offset: 2,
        width: 9,
        height: 22,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 21285,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 16,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 21397,
        x_offset: -1,
        y_offset: 4,
        width: 15,
        height: 21,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 21555,
        x_offset: -1,
        y_offset: 9,
        width: 13,
        height: 16,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 21659,
        x_offset: -1,
        y_offset: 4,
        width: 15,
        height: 21,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 21817,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 16,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 21929,
        x_offset: -1,
        y_offset: 4,
        width: 12,
        height: 20,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 22049,
        x_offset: -1,
        y_offset: 7,
        width: 15,
        height: 23,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 22222,
        x_offset: -1,
        y_offset: 4,
        width: 14,
        height: 20,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 22362,
        x_offset: -1,
        y_offset: 3,
        width: 7,
        height: 21,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 22436,
        x_offset: -2,
        y_offset: 3,
        width: 8,
        height: 27,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 22544,
        x_offset: -1,
        y_offset: 4,
        width: 15,
        height: 20,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 22694,
        x_offset: -1,
        y_offset: 4,
        width: 9,
        height: 21,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 22789,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 15,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 22947,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 15,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 23052,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 16,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 23172,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 21,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 23330,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 21,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 23477,
        x_offset: -1,
        y_offset: 9,
        width: 12,
        height: 15,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 23567,
        x_offset: -1,
        y_offset: 9,
        width: 13,
        height: 16,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 23671,
        x_offset: -1,
        y_offset: 6,
        width: 11,
        height: 19,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 23776,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 16,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 23888,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 23993,
        x_offset: -1,
        y_offset: 9,
        width: 19,
        height: 15,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 24136,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 15,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 24241,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 21,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 24388,
        x_offset: -1,
        y_offset: 9,
        width: 12,
        height: 15,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 24478,
        x_offset: -1,
        y_offset: 1,
        width: 9,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 24600,
        x_offset: -1,
        y_offset: 2,
        width: 8,
        height: 25,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 24700,
        x_offset: -1,
        y_offset: 1,
        width: 10,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 24835,
        x_offset: -1,
        y_offset: 12,
        width: 13,
        height: 12,
        advance: 13,
    },
];

pub(super) const CAPTION_MAP: [u8; 95] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
];

pub(super) const BODY_LINE_HEIGHT: u8 = 40;
pub(super) const BODY_GLYPHS: [RasterGlyph; 95] = [
    RasterGlyph {
        data_offset: 24913,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 24913,
        x_offset: -1,
        y_offset: 8,
        width: 8,
        height: 23,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 25005,
        x_offset: -1,
        y_offset: 8,
        width: 12,
        height: 22,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 25137,
        x_offset: -1,
        y_offset: 9,
        width: 17,
        height: 21,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 25316,
        x_offset: -1,
        y_offset: 4,
        width: 16,
        height: 31,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 25564,
        x_offset: -1,
        y_offset: 8,
        width: 24,
        height: 23,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 25840,
        x_offset: -1,
        y_offset: 8,
        width: 22,
        height: 23,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 26093,
        x_offset: -1,
        y_offset: 8,
        width: 7,
        height: 22,
        advance: 7,
    },
    RasterGlyph {
        data_offset: 26170,
        x_offset: -1,
        y_offset: 4,
        width: 10,
        height: 31,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 26325,
        x_offset: -1,
        y_offset: 4,
        width: 10,
        height: 31,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 26480,
        x_offset: -1,
        y_offset: 7,
        width: 14,
        height: 23,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 26641,
        x_offset: -1,
        y_offset: 13,
        width: 15,
        height: 17,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 26769,
        x_offset: -1,
        y_offset: 24,
        width: 8,
        height: 11,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 26813,
        x_offset: -1,
        y_offset: 18,
        width: 12,
        height: 12,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 26885,
        x_offset: -1,
        y_offset: 24,
        width: 8,
        height: 7,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 26913,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 28,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 27109,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 23,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 27305,
        x_offset: -1,
        y_offset: 9,
        width: 12,
        height: 21,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 27431,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 27596,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 23,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 27769,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 22,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 27956,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 28121,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 23,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 28305,
        x_offset: -1,
        y_offset: 9,
        width: 14,
        height: 22,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 28459,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 23,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 28655,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 23,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 28839,
        x_offset: -1,
        y_offset: 14,
        width: 8,
        height: 17,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 28907,
        x_offset: -1,
        y_offset: 14,
        width: 8,
        height: 21,
        advance: 8,
    },
    RasterGlyph {
        data_offset: 28991,
        x_offset: -1,
        y_offset: 12,
        width: 15,
        height: 18,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 29126,
        x_offset: -1,
        y_offset: 14,
        width: 15,
        height: 16,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 29246,
        x_offset: -1,
        y_offset: 12,
        width: 15,
        height: 18,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 29381,
        x_offset: -1,
        y_offset: 8,
        width: 15,
        height: 23,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 29554,
        x_offset: -1,
        y_offset: 8,
        width: 29,
        height: 28,
        advance: 30,
    },
    RasterGlyph {
        data_offset: 29960,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 22,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 30158,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 22,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 30356,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 23,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 30563,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 22,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 30772,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 22,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 30948,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 31124,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 23,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 31331,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 22,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 31540,
        x_offset: -1,
        y_offset: 8,
        width: 8,
        height: 22,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 31628,
        x_offset: -1,
        y_offset: 8,
        width: 8,
        height: 26,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 31732,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 22,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 31941,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 32117,
        x_offset: -1,
        y_offset: 8,
        width: 23,
        height: 22,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 32370,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 22,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 32579,
        x_offset: -1,
        y_offset: 8,
        width: 20,
        height: 23,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 32809,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 22,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 33007,
        x_offset: -1,
        y_offset: 8,
        width: 21,
        height: 25,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 33270,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 22,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 33479,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 23,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 33675,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 33862,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 23,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 34081,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 22,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 34279,
        x_offset: -1,
        y_offset: 8,
        width: 25,
        height: 22,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 34554,
        x_offset: -1,
        y_offset: 8,
        width: 17,
        height: 22,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 34741,
        x_offset: -1,
        y_offset: 8,
        width: 18,
        height: 22,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 34939,
        x_offset: -1,
        y_offset: 8,
        width: 16,
        height: 22,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 35115,
        x_offset: -1,
        y_offset: 5,
        width: 10,
        height: 29,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 35260,
        x_offset: -1,
        y_offset: 5,
        width: 14,
        height: 28,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 35456,
        x_offset: -1,
        y_offset: 5,
        width: 10,
        height: 29,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 35601,
        x_offset: -1,
        y_offset: 4,
        width: 16,
        height: 26,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 35809,
        x_offset: -1,
        y_offset: 28,
        width: 17,
        height: 6,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 35860,
        x_offset: -1,
        y_offset: 5,
        width: 10,
        height: 25,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 35985,
        x_offset: -1,
        y_offset: 12,
        width: 16,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 36137,
        x_offset: -1,
        y_offset: 7,
        width: 17,
        height: 24,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 36341,
        x_offset: -1,
        y_offset: 12,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 36484,
        x_offset: -1,
        y_offset: 7,
        width: 17,
        height: 24,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 36688,
        x_offset: -1,
        y_offset: 12,
        width: 16,
        height: 19,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 36840,
        x_offset: -1,
        y_offset: 7,
        width: 14,
        height: 23,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 37001,
        x_offset: -1,
        y_offset: 11,
        width: 17,
        height: 25,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 37214,
        x_offset: -1,
        y_offset: 7,
        width: 16,
        height: 23,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 37398,
        x_offset: -1,
        y_offset: 6,
        width: 8,
        height: 24,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 37494,
        x_offset: -2,
        y_offset: 6,
        width: 9,
        height: 30,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 37629,
        x_offset: -1,
        y_offset: 7,
        width: 17,
        height: 23,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 37825,
        x_offset: -1,
        y_offset: 7,
        width: 10,
        height: 24,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 37945,
        x_offset: -1,
        y_offset: 12,
        width: 24,
        height: 18,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 38161,
        x_offset: -1,
        y_offset: 12,
        width: 16,
        height: 18,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 38305,
        x_offset: -1,
        y_offset: 12,
        width: 17,
        height: 19,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 38467,
        x_offset: -1,
        y_offset: 12,
        width: 17,
        height: 24,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 38671,
        x_offset: -1,
        y_offset: 12,
        width: 16,
        height: 24,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 38863,
        x_offset: -1,
        y_offset: 12,
        width: 13,
        height: 18,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 38980,
        x_offset: -1,
        y_offset: 12,
        width: 15,
        height: 19,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 39123,
        x_offset: -1,
        y_offset: 9,
        width: 13,
        height: 22,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 39266,
        x_offset: -1,
        y_offset: 13,
        width: 16,
        height: 18,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 39410,
        x_offset: -1,
        y_offset: 13,
        width: 16,
        height: 17,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 39546,
        x_offset: -1,
        y_offset: 13,
        width: 22,
        height: 17,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 39733,
        x_offset: -1,
        y_offset: 13,
        width: 16,
        height: 17,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 39869,
        x_offset: -1,
        y_offset: 13,
        width: 16,
        height: 23,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 40053,
        x_offset: -1,
        y_offset: 13,
        width: 14,
        height: 17,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 40172,
        x_offset: -1,
        y_offset: 4,
        width: 10,
        height: 30,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 40322,
        x_offset: -1,
        y_offset: 5,
        width: 9,
        height: 28,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 40448,
        x_offset: -1,
        y_offset: 4,
        width: 11,
        height: 30,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 40613,
        x_offset: -1,
        y_offset: 17,
        width: 15,
        height: 13,
        advance: 15,
    },
];

pub(super) const BODY_MAP: [u8; 95] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
];

pub(super) const TITLE_LINE_HEIGHT: u8 = 48;
pub(super) const TITLE_GLYPHS: [RasterGlyph; 95] = [
    RasterGlyph {
        data_offset: 40711,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 40711,
        x_offset: -1,
        y_offset: 9,
        width: 10,
        height: 28,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 40851,
        x_offset: -1,
        y_offset: 9,
        width: 16,
        height: 27,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 41067,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 27,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 41351,
        x_offset: -1,
        y_offset: 4,
        width: 21,
        height: 38,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 41750,
        x_offset: -1,
        y_offset: 8,
        width: 32,
        height: 30,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 42230,
        x_offset: -1,
        y_offset: 8,
        width: 28,
        height: 29,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 42636,
        x_offset: -1,
        y_offset: 9,
        width: 9,
        height: 27,
        advance: 9,
    },
    RasterGlyph {
        data_offset: 42758,
        x_offset: -1,
        y_offset: 3,
        width: 13,
        height: 39,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 43012,
        x_offset: -1,
        y_offset: 3,
        width: 13,
        height: 39,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 43266,
        x_offset: -1,
        y_offset: 7,
        width: 18,
        height: 29,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 43527,
        x_offset: -1,
        y_offset: 14,
        width: 19,
        height: 22,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 43736,
        x_offset: -1,
        y_offset: 28,
        width: 10,
        height: 15,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 43811,
        x_offset: -1,
        y_offset: 20,
        width: 15,
        height: 16,
        advance: 16,
    },
    RasterGlyph {
        data_offset: 43931,
        x_offset: -1,
        y_offset: 28,
        width: 10,
        height: 9,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 43976,
        x_offset: -1,
        y_offset: 4,
        width: 18,
        height: 36,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 44300,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 28,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 44594,
        x_offset: -1,
        y_offset: 9,
        width: 15,
        height: 27,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 44797,
        x_offset: -1,
        y_offset: 9,
        width: 19,
        height: 27,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 45054,
        x_offset: -1,
        y_offset: 9,
        width: 19,
        height: 28,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 45320,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 27,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 45604,
        x_offset: -1,
        y_offset: 9,
        width: 20,
        height: 28,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 45884,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 28,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 46178,
        x_offset: -1,
        y_offset: 9,
        width: 18,
        height: 28,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 46430,
        x_offset: -1,
        y_offset: 9,
        width: 22,
        height: 28,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 46738,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 28,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 47032,
        x_offset: -1,
        y_offset: 15,
        width: 10,
        height: 22,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 47142,
        x_offset: -1,
        y_offset: 15,
        width: 10,
        height: 28,
        advance: 10,
    },
    RasterGlyph {
        data_offset: 47282,
        x_offset: -1,
        y_offset: 13,
        width: 19,
        height: 23,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 47501,
        x_offset: -1,
        y_offset: 16,
        width: 19,
        height: 20,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 47691,
        x_offset: -1,
        y_offset: 13,
        width: 19,
        height: 23,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 47910,
        x_offset: -1,
        y_offset: 8,
        width: 19,
        height: 29,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 48186,
        x_offset: -1,
        y_offset: 8,
        width: 37,
        height: 36,
        advance: 38,
    },
    RasterGlyph {
        data_offset: 48852,
        x_offset: -2,
        y_offset: 9,
        width: 25,
        height: 27,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 49190,
        x_offset: -1,
        y_offset: 9,
        width: 23,
        height: 27,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 49501,
        x_offset: -1,
        y_offset: 8,
        width: 22,
        height: 29,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 49820,
        x_offset: -1,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 50144,
        x_offset: -1,
        y_offset: 9,
        width: 20,
        height: 27,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 50414,
        x_offset: -1,
        y_offset: 9,
        width: 19,
        height: 27,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 50671,
        x_offset: -1,
        y_offset: 8,
        width: 24,
        height: 29,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 51019,
        x_offset: -1,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 51343,
        x_offset: -1,
        y_offset: 9,
        width: 10,
        height: 27,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 51478,
        x_offset: -2,
        y_offset: 9,
        width: 12,
        height: 33,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 51676,
        x_offset: -1,
        y_offset: 9,
        width: 25,
        height: 27,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 52014,
        x_offset: -1,
        y_offset: 9,
        width: 20,
        height: 27,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 52284,
        x_offset: -1,
        y_offset: 9,
        width: 29,
        height: 27,
        advance: 30,
    },
    RasterGlyph {
        data_offset: 52676,
        x_offset: -1,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 53000,
        x_offset: -1,
        y_offset: 8,
        width: 26,
        height: 29,
        advance: 26,
    },
    RasterGlyph {
        data_offset: 53377,
        x_offset: -1,
        y_offset: 9,
        width: 23,
        height: 27,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 53688,
        x_offset: -1,
        y_offset: 8,
        width: 27,
        height: 33,
        advance: 26,
    },
    RasterGlyph {
        data_offset: 54134,
        x_offset: -1,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 54458,
        x_offset: -1,
        y_offset: 8,
        width: 22,
        height: 29,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 54777,
        x_offset: -1,
        y_offset: 9,
        width: 21,
        height: 27,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 55061,
        x_offset: -1,
        y_offset: 9,
        width: 24,
        height: 28,
        advance: 25,
    },
    RasterGlyph {
        data_offset: 55397,
        x_offset: -2,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 55721,
        x_offset: -1,
        y_offset: 9,
        width: 32,
        height: 27,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 56153,
        x_offset: -1,
        y_offset: 9,
        width: 23,
        height: 27,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 56464,
        x_offset: -2,
        y_offset: 9,
        width: 24,
        height: 27,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 56788,
        x_offset: -1,
        y_offset: 9,
        width: 20,
        height: 27,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 57058,
        x_offset: -1,
        y_offset: 4,
        width: 13,
        height: 37,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 57299,
        x_offset: -1,
        y_offset: 4,
        width: 18,
        height: 36,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 57623,
        x_offset: -1,
        y_offset: 4,
        width: 12,
        height: 37,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 57845,
        x_offset: -1,
        y_offset: 3,
        width: 21,
        height: 33,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 58192,
        x_offset: -1,
        y_offset: 34,
        width: 21,
        height: 8,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 58276,
        x_offset: -1,
        y_offset: 4,
        width: 13,
        height: 32,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 58484,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 23,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 58726,
        x_offset: -1,
        y_offset: 6,
        width: 22,
        height: 31,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 59067,
        x_offset: -1,
        y_offset: 14,
        width: 19,
        height: 23,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 59286,
        x_offset: -1,
        y_offset: 6,
        width: 21,
        height: 31,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 59612,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 23,
        advance: 21,
    },
    RasterGlyph {
        data_offset: 59854,
        x_offset: -1,
        y_offset: 6,
        width: 17,
        height: 30,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 60109,
        x_offset: -1,
        y_offset: 12,
        width: 22,
        height: 32,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 60461,
        x_offset: -1,
        y_offset: 6,
        width: 21,
        height: 30,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 60776,
        x_offset: -1,
        y_offset: 5,
        width: 10,
        height: 31,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 60931,
        x_offset: -3,
        y_offset: 5,
        width: 12,
        height: 39,
        advance: 11,
    },
    RasterGlyph {
        data_offset: 61165,
        x_offset: -1,
        y_offset: 6,
        width: 22,
        height: 30,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 61495,
        x_offset: -1,
        y_offset: 6,
        width: 13,
        height: 31,
        advance: 12,
    },
    RasterGlyph {
        data_offset: 61697,
        x_offset: -1,
        y_offset: 14,
        width: 31,
        height: 22,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 62038,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 22,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 62269,
        x_offset: -1,
        y_offset: 14,
        width: 22,
        height: 23,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 62522,
        x_offset: -1,
        y_offset: 14,
        width: 22,
        height: 30,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 62852,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 30,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 63167,
        x_offset: -1,
        y_offset: 14,
        width: 17,
        height: 22,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 63354,
        x_offset: -1,
        y_offset: 14,
        width: 19,
        height: 23,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 63573,
        x_offset: -1,
        y_offset: 10,
        width: 16,
        height: 27,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 63789,
        x_offset: -1,
        y_offset: 14,
        width: 20,
        height: 23,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 64019,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 22,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 64250,
        x_offset: -1,
        y_offset: 14,
        width: 29,
        height: 22,
        advance: 27,
    },
    RasterGlyph {
        data_offset: 64569,
        x_offset: -2,
        y_offset: 14,
        width: 22,
        height: 22,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 64811,
        x_offset: -1,
        y_offset: 14,
        width: 21,
        height: 30,
        advance: 19,
    },
    RasterGlyph {
        data_offset: 65126,
        x_offset: -1,
        y_offset: 14,
        width: 18,
        height: 22,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 65324,
        x_offset: -1,
        y_offset: 3,
        width: 13,
        height: 38,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 65571,
        x_offset: -1,
        y_offset: 4,
        width: 12,
        height: 36,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 65787,
        x_offset: -1,
        y_offset: 3,
        width: 14,
        height: 38,
        advance: 13,
    },
    RasterGlyph {
        data_offset: 66053,
        x_offset: -1,
        y_offset: 19,
        width: 20,
        height: 17,
        advance: 19,
    },
];

pub(super) const TITLE_MAP: [u8; 95] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
    74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
];

pub(super) const HEADLINE_LINE_HEIGHT: u8 = 68;
pub(super) const HEADLINE_GLYPHS: [RasterGlyph; 68] = [
    RasterGlyph {
        data_offset: 66223,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 15,
    },
    RasterGlyph {
        data_offset: 66223,
        x_offset: -2,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 66961,
        x_offset: -1,
        y_offset: 10,
        width: 35,
        height: 41,
        advance: 35,
    },
    RasterGlyph {
        data_offset: 67679,
        x_offset: -1,
        y_offset: 9,
        width: 34,
        height: 43,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 68410,
        x_offset: -1,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 37,
    },
    RasterGlyph {
        data_offset: 69148,
        x_offset: -1,
        y_offset: 10,
        width: 30,
        height: 41,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 69763,
        x_offset: -1,
        y_offset: 10,
        width: 29,
        height: 41,
        advance: 28,
    },
    RasterGlyph {
        data_offset: 70358,
        x_offset: -1,
        y_offset: 9,
        width: 35,
        height: 43,
        advance: 37,
    },
    RasterGlyph {
        data_offset: 71111,
        x_offset: -1,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 39,
    },
    RasterGlyph {
        data_offset: 71849,
        x_offset: -1,
        y_offset: 10,
        width: 14,
        height: 41,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 72136,
        x_offset: -2,
        y_offset: 10,
        width: 17,
        height: 50,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 72561,
        x_offset: -1,
        y_offset: 10,
        width: 37,
        height: 41,
        advance: 35,
    },
    RasterGlyph {
        data_offset: 73320,
        x_offset: -1,
        y_offset: 10,
        width: 30,
        height: 41,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 73935,
        x_offset: -1,
        y_offset: 10,
        width: 44,
        height: 41,
        advance: 45,
    },
    RasterGlyph {
        data_offset: 74837,
        x_offset: -1,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 39,
    },
    RasterGlyph {
        data_offset: 75575,
        x_offset: -1,
        y_offset: 9,
        width: 39,
        height: 43,
        advance: 40,
    },
    RasterGlyph {
        data_offset: 76414,
        x_offset: -1,
        y_offset: 10,
        width: 34,
        height: 41,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 77111,
        x_offset: -1,
        y_offset: 9,
        width: 41,
        height: 50,
        advance: 40,
    },
    RasterGlyph {
        data_offset: 78136,
        x_offset: -1,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 35,
    },
    RasterGlyph {
        data_offset: 78874,
        x_offset: -1,
        y_offset: 9,
        width: 32,
        height: 43,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 79562,
        x_offset: -1,
        y_offset: 10,
        width: 32,
        height: 41,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 80218,
        x_offset: -1,
        y_offset: 10,
        width: 35,
        height: 42,
        advance: 38,
    },
    RasterGlyph {
        data_offset: 80953,
        x_offset: -2,
        y_offset: 10,
        width: 35,
        height: 41,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 81671,
        x_offset: -1,
        y_offset: 10,
        width: 48,
        height: 41,
        advance: 48,
    },
    RasterGlyph {
        data_offset: 82655,
        x_offset: -1,
        y_offset: 10,
        width: 34,
        height: 41,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 83352,
        x_offset: -2,
        y_offset: 10,
        width: 36,
        height: 41,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 84090,
        x_offset: -1,
        y_offset: 10,
        width: 30,
        height: 41,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 84705,
        x_offset: -1,
        y_offset: 18,
        width: 31,
        height: 34,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 85232,
        x_offset: -1,
        y_offset: 6,
        width: 33,
        height: 46,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 85991,
        x_offset: -1,
        y_offset: 18,
        width: 28,
        height: 34,
        advance: 28,
    },
    RasterGlyph {
        data_offset: 86467,
        x_offset: -1,
        y_offset: 6,
        width: 32,
        height: 46,
        advance: 35,
    },
    RasterGlyph {
        data_offset: 87203,
        x_offset: -1,
        y_offset: 18,
        width: 31,
        height: 34,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 87730,
        x_offset: -1,
        y_offset: 6,
        width: 26,
        height: 45,
        advance: 20,
    },
    RasterGlyph {
        data_offset: 88315,
        x_offset: -1,
        y_offset: 15,
        width: 33,
        height: 49,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 89124,
        x_offset: -1,
        y_offset: 6,
        width: 31,
        height: 45,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 89822,
        x_offset: -1,
        y_offset: 4,
        width: 15,
        height: 47,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 90175,
        x_offset: -3,
        y_offset: 4,
        width: 17,
        height: 60,
        advance: 17,
    },
    RasterGlyph {
        data_offset: 90685,
        x_offset: -1,
        y_offset: 6,
        width: 33,
        height: 45,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 91428,
        x_offset: -1,
        y_offset: 6,
        width: 19,
        height: 46,
        advance: 18,
    },
    RasterGlyph {
        data_offset: 91865,
        x_offset: -1,
        y_offset: 18,
        width: 46,
        height: 33,
        advance: 49,
    },
    RasterGlyph {
        data_offset: 92624,
        x_offset: -1,
        y_offset: 18,
        width: 31,
        height: 33,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 93136,
        x_offset: -1,
        y_offset: 18,
        width: 33,
        height: 34,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 93697,
        x_offset: -1,
        y_offset: 18,
        width: 33,
        height: 46,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 94456,
        x_offset: -1,
        y_offset: 18,
        width: 31,
        height: 46,
        advance: 34,
    },
    RasterGlyph {
        data_offset: 95169,
        x_offset: -1,
        y_offset: 18,
        width: 24,
        height: 33,
        advance: 23,
    },
    RasterGlyph {
        data_offset: 95565,
        x_offset: -1,
        y_offset: 18,
        width: 28,
        height: 34,
        advance: 28,
    },
    RasterGlyph {
        data_offset: 96041,
        x_offset: -1,
        y_offset: 11,
        width: 24,
        height: 41,
        advance: 22,
    },
    RasterGlyph {
        data_offset: 96533,
        x_offset: -1,
        y_offset: 19,
        width: 30,
        height: 33,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 97028,
        x_offset: -1,
        y_offset: 19,
        width: 31,
        height: 32,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 97524,
        x_offset: -1,
        y_offset: 19,
        width: 43,
        height: 32,
        advance: 42,
    },
    RasterGlyph {
        data_offset: 98212,
        x_offset: -2,
        y_offset: 19,
        width: 32,
        height: 32,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 98724,
        x_offset: -1,
        y_offset: 19,
        width: 31,
        height: 45,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 99422,
        x_offset: -1,
        y_offset: 19,
        width: 26,
        height: 32,
        advance: 26,
    },
    RasterGlyph {
        data_offset: 99838,
        x_offset: -1,
        y_offset: 10,
        width: 32,
        height: 42,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 100510,
        x_offset: -1,
        y_offset: 11,
        width: 22,
        height: 40,
        advance: 26,
    },
    RasterGlyph {
        data_offset: 100950,
        x_offset: -1,
        y_offset: 10,
        width: 29,
        height: 41,
        advance: 29,
    },
    RasterGlyph {
        data_offset: 101545,
        x_offset: -1,
        y_offset: 10,
        width: 29,
        height: 42,
        advance: 30,
    },
    RasterGlyph {
        data_offset: 102154,
        x_offset: -1,
        y_offset: 10,
        width: 32,
        height: 41,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 102810,
        x_offset: -1,
        y_offset: 11,
        width: 29,
        height: 41,
        advance: 30,
    },
    RasterGlyph {
        data_offset: 103405,
        x_offset: -1,
        y_offset: 10,
        width: 32,
        height: 42,
        advance: 32,
    },
    RasterGlyph {
        data_offset: 104077,
        x_offset: -1,
        y_offset: 11,
        width: 27,
        height: 41,
        advance: 27,
    },
    RasterGlyph {
        data_offset: 104631,
        x_offset: -1,
        y_offset: 10,
        width: 32,
        height: 42,
        advance: 33,
    },
    RasterGlyph {
        data_offset: 105303,
        x_offset: -1,
        y_offset: 10,
        width: 31,
        height: 43,
        advance: 31,
    },
    RasterGlyph {
        data_offset: 105970,
        x_offset: -1,
        y_offset: 28,
        width: 22,
        height: 23,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 106223,
        x_offset: -1,
        y_offset: 40,
        width: 14,
        height: 12,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 106307,
        x_offset: -1,
        y_offset: 3,
        width: 27,
        height: 55,
        advance: 30,
    },
    RasterGlyph {
        data_offset: 107050,
        x_offset: -1,
        y_offset: 20,
        width: 14,
        height: 32,
        advance: 14,
    },
    RasterGlyph {
        data_offset: 107274,
        x_offset: -1,
        y_offset: 9,
        width: 28,
        height: 43,
        advance: 27,
    },
];

pub(super) const HEADLINE_MAP: [u8; 95] = [
    0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 63, 64, 65, 53, 54, 55, 56, 57,
    58, 59, 60, 61, 62, 66, 255, 255, 255, 255, 67, 255, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
    14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 255, 255, 255, 255, 255, 255, 27, 28, 29,
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
    255, 255, 255, 255,
];

pub(super) const DISPLAY_LINE_HEIGHT: u8 = 116;
pub(super) const DISPLAY_GLYPHS: [RasterGlyph; 13] = [
    RasterGlyph {
        data_offset: 107876,
        x_offset: 0,
        y_offset: 0,
        width: 0,
        height: 0,
        advance: 26,
    },
    RasterGlyph {
        data_offset: 107876,
        x_offset: -1,
        y_offset: 23,
        width: 51,
        height: 70,
        advance: 55,
    },
    RasterGlyph {
        data_offset: 109661,
        x_offset: -1,
        y_offset: 24,
        width: 34,
        height: 67,
        advance: 43,
    },
    RasterGlyph {
        data_offset: 110800,
        x_offset: -1,
        y_offset: 23,
        width: 45,
        height: 68,
        advance: 49,
    },
    RasterGlyph {
        data_offset: 112330,
        x_offset: -1,
        y_offset: 23,
        width: 45,
        height: 70,
        advance: 49,
    },
    RasterGlyph {
        data_offset: 113905,
        x_offset: -1,
        y_offset: 23,
        width: 51,
        height: 68,
        advance: 52,
    },
    RasterGlyph {
        data_offset: 115639,
        x_offset: -1,
        y_offset: 24,
        width: 46,
        height: 69,
        advance: 49,
    },
    RasterGlyph {
        data_offset: 117226,
        x_offset: -1,
        y_offset: 23,
        width: 50,
        height: 70,
        advance: 52,
    },
    RasterGlyph {
        data_offset: 118976,
        x_offset: -1,
        y_offset: 24,
        width: 42,
        height: 68,
        advance: 44,
    },
    RasterGlyph {
        data_offset: 120404,
        x_offset: -1,
        y_offset: 23,
        width: 51,
        height: 70,
        advance: 54,
    },
    RasterGlyph {
        data_offset: 122189,
        x_offset: -1,
        y_offset: 23,
        width: 48,
        height: 71,
        advance: 51,
    },
    RasterGlyph {
        data_offset: 123893,
        x_offset: -1,
        y_offset: 41,
        width: 21,
        height: 52,
        advance: 24,
    },
    RasterGlyph {
        data_offset: 124439,
        x_offset: -1,
        y_offset: 21,
        width: 44,
        height: 72,
        advance: 45,
    },
];

pub(super) const DISPLAY_MAP: [u8; 95] = [
    0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 1, 2, 3, 4, 5, 6,
    7, 8, 9, 10, 11, 255, 255, 255, 255, 12, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
];
