#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$WORKSPACE_ROOT"

feature_list_contains() {
  local requested="${1//,/ }"
  local expected="$2"
  local feature
  for feature in $requested; do
    if [[ "$feature" == "$expected" || "$feature" == */"$expected" ]]; then
      return 0
    fi
  done
  return 1
}

append_feature() {
  local requested="$1"
  local feature="$2"
  if feature_list_contains "$requested" "$feature"; then
    printf '%s' "$requested"
  elif [[ -n "$requested" ]]; then
    printf '%s,%s' "$requested" "$feature"
  else
    printf '%s' "$feature"
  fi
}

PROFILE="${BNDROID_PROFILE:-debug}"
TARGET_ROOT="${CARGO_TARGET_DIR:-$WORKSPACE_ROOT/target}"
# Cargo resolves a relative target directory from the workspace, but build.rs
# runs with the package directory as its cwd. Export absolute embedded-image
# paths so both callers agree even when CARGO_TARGET_DIR is relative.
if [[ "$TARGET_ROOT" != /* ]]; then
  TARGET_ROOT="$WORKSPACE_ROOT/$TARGET_ROOT"
fi
mkdir -p "$TARGET_ROOT"
TARGET_ROOT="$(cd -- "$TARGET_ROOT" && pwd)"
export CARGO_TARGET_DIR="$TARGET_ROOT"

KERNEL_FEATURES="${BNDROID_KERNEL_FEATURES:-}"
USERSPACE_FEATURES="${BNDROID_USERSPACE_FEATURES:-}"
KERNEL_MOBILE_UI_RUNTIME=0
KERNEL_ANDROIDBOX_DEX0=0
KERNEL_ANDROIDBOX_APK_INSTALL0=0
KERNEL_ANDROIDBOX_EL0_RUNTIME0=0
KERNEL_ANDROIDBOX_INTERACTIVE0=0
KERNEL_ANDROIDBOX_PROCESS0=0
KERNEL_ANDROIDBOX_RESTART0=0
KERNEL_ANDROIDBOX_SCENE_RPC2=0
KERNEL_ANDROIDBOX_MULTIACTION3=0
KERNEL_ANDROIDBOX_APK_ENVELOPE4=0
KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=0
KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=0
KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=0
KERNEL_ANDROIDBOX_MULTIPACKAGE4=0
KERNEL_ANDROIDBOX_ICON_RESOURCES5=0
KERNEL_ANDROIDBOX_DENSITY_ICONS7=0
KERNEL_ANDROIDBOX_DEX_METHODS8=0
KERNEL_ANDROIDBOX_DEX_INSTANCE9=0
KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10=0
KERNEL_ANDROIDBOX_ACTIVITY_STATE11=0
KERNEL_ANDROIDBOX_STRING_TEXT12=0
KERNEL_ANDROIDBOX_STRING_BUILDER13=0
KERNEL_ANDROIDBOX_LAYOUT_ROW14=0
KERNEL_ANDROIDBOX_LAYOUT_WEIGHT15=0
KERNEL_ANDROIDBOX_LAYOUT_SPACING16=0
KERNEL_ANDROIDBOX_LAYOUT_DIRECTIONAL17=0
KERNEL_ANDROIDBOX_LAYOUT_SIZE18=0
KERNEL_ANDROIDBOX_LAYOUT_MIXED19=0
KERNEL_APP_DATA_RUNTIME=0
KERNEL_APP_DATA_ASYNC_RECOVERY_RUNTIME=0
KERNEL_STORAGE_IRQ_TIMEOUT_SELF_TEST=0
KERNEL_STORAGE_SERVER_RUNTIME=0
KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=0
KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=0
KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=0
KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=0
KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=0
KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=0
KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=0
KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=0
KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=0
KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=0
KERNEL_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME=0
USER_APP_DATA_RUNTIME=0
USER_APP_DATA_ASYNC_RECOVERY_RUNTIME=0
USER_STORAGE_SERVER_RUNTIME=0
USER_STORAGE_SERVER_RECOVERY_RUNTIME=0
USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=0
USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=0
USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=0
USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=0
USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=0
USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=0
USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=0
USER_UNIFIED_PRODUCT_RUNTIME=0
USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=0
USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=0
USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=0
USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=0
USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=0
USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=0
USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=0
USER_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=0
USER_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=0
USER_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME=0
USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=0
USER_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=0
USER_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=0
USER_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME=0
USER_MOBILE_UI_RUNTIME=0
USER_ANDROIDBOX_DEX0=0
USER_ANDROIDBOX_APK_INSTALL0=0
USER_ANDROIDBOX_EL0_RUNTIME0=0
USER_ANDROIDBOX_INTERACTIVE0=0
USER_ANDROIDBOX_PROCESS0=0
USER_ANDROIDBOX_RESTART0=0
USER_ANDROIDBOX_SCENE_RPC2=0
USER_ANDROIDBOX_MULTIACTION3=0
USER_ANDROIDBOX_APK_ENVELOPE4=0
USER_ANDROIDBOX_RUNTIME_UNINSTALL1=0
USER_ANDROIDBOX_RUNTIME_INSTALL2=0
USER_ANDROIDBOX_MANIFEST_CATALOG3=0
USER_ANDROIDBOX_MULTIPACKAGE4=0
USER_ANDROIDBOX_ICON_RESOURCES5=0
USER_ANDROIDBOX_DENSITY_ICONS7=0
USER_ANDROIDBOX_DEX_METHODS8=0
USER_ANDROIDBOX_DEX_INSTANCE9=0
USER_ANDROIDBOX_ACTIVITY_FIELDS10=0
USER_ANDROIDBOX_ACTIVITY_STATE11=0
USER_ANDROIDBOX_STRING_TEXT12=0
USER_ANDROIDBOX_STRING_BUILDER13=0
USER_ANDROIDBOX_LAYOUT_ROW14=0
USER_ANDROIDBOX_LAYOUT_WEIGHT15=0
USER_ANDROIDBOX_LAYOUT_SPACING16=0
USER_ANDROIDBOX_LAYOUT_DIRECTIONAL17=0
USER_ANDROIDBOX_LAYOUT_SIZE18=0
USER_ANDROIDBOX_LAYOUT_MIXED19=0

if feature_list_contains "$KERNEL_FEATURES" "mobile-ui-runtime"; then
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-dex0"; then
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-apk-install0"; then
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-el0-runtime0"; then
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-interactive0"; then
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-process0"; then
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-restart0"; then
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-scene-rpc2"; then
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-multiaction3"; then
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-apk-envelope4"; then
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-runtime-uninstall1"; then
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-runtime-install2"; then
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-manifest-catalog3"; then
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-multipackage4"; then
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-icon-resources5"; then
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-density-icons7"; then
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-dex-methods8"; then
  KERNEL_ANDROIDBOX_DEX_METHODS8=1
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-dex-instance9"; then
  KERNEL_ANDROIDBOX_DEX_INSTANCE9=1
  KERNEL_ANDROIDBOX_DEX_METHODS8=1
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-activity-fields10"; then
  KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10=1
  KERNEL_ANDROIDBOX_DEX_INSTANCE9=1
  KERNEL_ANDROIDBOX_DEX_METHODS8=1
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-activity-state11"; then
  KERNEL_ANDROIDBOX_ACTIVITY_STATE11=1
  KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10=1
  KERNEL_ANDROIDBOX_DEX_INSTANCE9=1
  KERNEL_ANDROIDBOX_DEX_METHODS8=1
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-mixed19"; then
  KERNEL_ANDROIDBOX_LAYOUT_MIXED19=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-layout-size18")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-size18"; then
  KERNEL_ANDROIDBOX_LAYOUT_SIZE18=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-layout-directional17")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-directional17"; then
  KERNEL_ANDROIDBOX_LAYOUT_DIRECTIONAL17=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-layout-spacing16")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-spacing16"; then
  KERNEL_ANDROIDBOX_LAYOUT_SPACING16=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-layout-weight15")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-weight15"; then
  KERNEL_ANDROIDBOX_LAYOUT_WEIGHT15=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-layout-row14")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-layout-row14"; then
  KERNEL_ANDROIDBOX_LAYOUT_ROW14=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-string-builder13")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-string-builder13"; then
  KERNEL_ANDROIDBOX_STRING_BUILDER13=1
  KERNEL_FEATURES="$(append_feature "$KERNEL_FEATURES" "androidbox-string-text12")"
fi
if feature_list_contains "$KERNEL_FEATURES" "androidbox-string-text12"; then
  KERNEL_ANDROIDBOX_STRING_TEXT12=1
  KERNEL_ANDROIDBOX_ACTIVITY_STATE11=1
  KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10=1
  KERNEL_ANDROIDBOX_DEX_INSTANCE9=1
  KERNEL_ANDROIDBOX_DEX_METHODS8=1
  KERNEL_ANDROIDBOX_DENSITY_ICONS7=1
  KERNEL_ANDROIDBOX_ICON_RESOURCES5=1
  KERNEL_ANDROIDBOX_MULTIPACKAGE4=1
  KERNEL_ANDROIDBOX_MANIFEST_CATALOG3=1
  KERNEL_ANDROIDBOX_RUNTIME_INSTALL2=1
  KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  KERNEL_ANDROIDBOX_APK_ENVELOPE4=1
  KERNEL_ANDROIDBOX_MULTIACTION3=1
  KERNEL_ANDROIDBOX_SCENE_RPC2=1
  KERNEL_ANDROIDBOX_RESTART0=1
  KERNEL_ANDROIDBOX_PROCESS0=1
  KERNEL_ANDROIDBOX_INTERACTIVE0=1
  KERNEL_ANDROIDBOX_EL0_RUNTIME0=1
  KERNEL_ANDROIDBOX_APK_INSTALL0=1
  KERNEL_ANDROIDBOX_DEX0=1
  KERNEL_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "app-data-async-recovery-runtime"; then
  KERNEL_APP_DATA_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_APP_DATA_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "app-data-runtime"; then
  KERNEL_APP_DATA_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "storage-irq-timeout-self-test"; then
  KERNEL_STORAGE_IRQ_TIMEOUT_SELF_TEST=1
fi

if feature_list_contains "$KERNEL_FEATURES" "unified-product-signed-maintenance-plan-runtime"; then
  KERNEL_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "unified-product-maintenance-plan-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "unified-product-maintenance-step-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "unified-product-maintenance-execution-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if [[ "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME" -eq 1 ]] \
  || feature_list_contains "$KERNEL_FEATURES" "unified-product-maintenance-authorization-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-key-rotation-runtime"; then
  KERNEL_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-persistent-rollback-runtime"; then
  KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-verified-manifest-runtime"; then
  KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-event-supervision-runtime"; then
  KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-manifest-supervision-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-continuous-supervision-runtime"; then
  KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-psci-shutdown-runtime"; then
  KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-multiservice-liveness-runtime"; then
  KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-liveness-runtime"; then
  KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "unified-product-runtime"; then
  KERNEL_UNIFIED_PRODUCT_RUNTIME=1
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "resident-platform-shutdown-runtime"; then
  KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-shutdown-orchestration-runtime"; then
  KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-clean-shutdown-runtime"; then
  KERNEL_STORAGE_SERVER_CLEAN_SHUTDOWN_RUNTIME=1
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "storage-server-persistent-health-runtime"; then
  KERNEL_STORAGE_SERVER_PERSISTENT_HEALTH_RUNTIME=1
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "storage-server-terminal-quarantine-runtime"; then
  KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
fi
if feature_list_contains "$KERNEL_FEATURES" "storage-server-owner-liveness-runtime"; then
  KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-fault-policy-runtime"; then
  KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-async-recovery-runtime"; then
  KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-repeated-recovery-runtime"; then
  KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-recovery-runtime"; then
  KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME=1
  KERNEL_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$KERNEL_FEATURES" "storage-server-runtime"; then
  KERNEL_STORAGE_SERVER_RUNTIME=1
fi

if [[ "$KERNEL_APP_DATA_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_RUNTIME" -eq 1 ]]; then
  echo "AppData runtime and StorageServer runtime profiles are mutually exclusive." >&2
  exit 2
fi
if [[ "$KERNEL_APP_DATA_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_IRQ_TIMEOUT_SELF_TEST" -eq 1 ]]; then
  echo "AppData runtime and low-level timeout self-test profiles are mutually exclusive." >&2
  exit 2
fi
if [[ "$KERNEL_STORAGE_IRQ_TIMEOUT_SELF_TEST" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_RUNTIME" -eq 1 ]]; then
  echo "low-level timeout self-test and StorageServer runtime profiles are mutually exclusive." >&2
  exit 2
fi

if feature_list_contains "$USERSPACE_FEATURES" "mobile-ui-runtime"; then
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-dex0"; then
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-apk-install0"; then
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-el0-runtime0"; then
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-interactive0"; then
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-process0"; then
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-restart0"; then
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-scene-rpc2"; then
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-multiaction3"; then
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-apk-envelope4"; then
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-runtime-uninstall1"; then
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-runtime-install2"; then
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-manifest-catalog3"; then
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-multipackage4"; then
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-icon-resources5"; then
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-density-icons7"; then
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-dex-methods8"; then
  USER_ANDROIDBOX_DEX_METHODS8=1
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-dex-instance9"; then
  USER_ANDROIDBOX_DEX_INSTANCE9=1
  USER_ANDROIDBOX_DEX_METHODS8=1
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-activity-fields10"; then
  USER_ANDROIDBOX_ACTIVITY_FIELDS10=1
  USER_ANDROIDBOX_DEX_INSTANCE9=1
  USER_ANDROIDBOX_DEX_METHODS8=1
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-activity-state11"; then
  USER_ANDROIDBOX_ACTIVITY_STATE11=1
  USER_ANDROIDBOX_ACTIVITY_FIELDS10=1
  USER_ANDROIDBOX_DEX_INSTANCE9=1
  USER_ANDROIDBOX_DEX_METHODS8=1
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-mixed19"; then
  USER_ANDROIDBOX_LAYOUT_MIXED19=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-size18")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-size18"; then
  USER_ANDROIDBOX_LAYOUT_SIZE18=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-directional17")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-directional17"; then
  USER_ANDROIDBOX_LAYOUT_DIRECTIONAL17=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-spacing16")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-spacing16"; then
  USER_ANDROIDBOX_LAYOUT_SPACING16=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-weight15")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-weight15"; then
  USER_ANDROIDBOX_LAYOUT_WEIGHT15=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-row14")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-layout-row14"; then
  USER_ANDROIDBOX_LAYOUT_ROW14=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-string-builder13")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-string-builder13"; then
  USER_ANDROIDBOX_STRING_BUILDER13=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-string-text12")"
fi
if feature_list_contains "$USERSPACE_FEATURES" "androidbox-string-text12"; then
  USER_ANDROIDBOX_STRING_TEXT12=1
  USER_ANDROIDBOX_ACTIVITY_STATE11=1
  USER_ANDROIDBOX_ACTIVITY_FIELDS10=1
  USER_ANDROIDBOX_DEX_INSTANCE9=1
  USER_ANDROIDBOX_DEX_METHODS8=1
  USER_ANDROIDBOX_DENSITY_ICONS7=1
  USER_ANDROIDBOX_ICON_RESOURCES5=1
  USER_ANDROIDBOX_MULTIPACKAGE4=1
  USER_ANDROIDBOX_MANIFEST_CATALOG3=1
  USER_ANDROIDBOX_RUNTIME_INSTALL2=1
  USER_ANDROIDBOX_RUNTIME_UNINSTALL1=1
  USER_ANDROIDBOX_APK_ENVELOPE4=1
  USER_ANDROIDBOX_MULTIACTION3=1
  USER_ANDROIDBOX_SCENE_RPC2=1
  USER_ANDROIDBOX_RESTART0=1
  USER_ANDROIDBOX_PROCESS0=1
  USER_ANDROIDBOX_INTERACTIVE0=1
  USER_ANDROIDBOX_EL0_RUNTIME0=1
  USER_ANDROIDBOX_APK_INSTALL0=1
  USER_ANDROIDBOX_DEX0=1
  USER_MOBILE_UI_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "app-data-async-recovery-runtime"; then
  USER_APP_DATA_ASYNC_RECOVERY_RUNTIME=1
  USER_APP_DATA_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "app-data-runtime"; then
  USER_APP_DATA_RUNTIME=1
fi

if feature_list_contains "$USERSPACE_FEATURES" "unified-product-signed-maintenance-plan-runtime"; then
  USER_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "unified-product-maintenance-plan-runtime"; then
  USER_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "unified-product-maintenance-step-runtime"; then
  USER_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME=1
  USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "unified-product-maintenance-execution-runtime"; then
  USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME=1
fi
if [[ "$USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME" -eq 1 ]] \
  || feature_list_contains "$USERSPACE_FEATURES" "unified-product-maintenance-authorization-runtime"; then
  USER_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME=1
  USER_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-key-rotation-runtime"; then
  USER_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-persistent-rollback-runtime"; then
  USER_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME=1
  USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-verified-manifest-runtime"; then
  USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME=1
  USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-event-supervision-runtime"; then
  USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-manifest-supervision-runtime"; then
  USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-continuous-supervision-runtime"; then
  USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME=1
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-psci-shutdown-runtime"; then
  USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME=1
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-multiservice-liveness-runtime"; then
  USER_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-liveness-runtime"; then
  USER_UNIFIED_PRODUCT_LIVENESS_RUNTIME=1
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "unified-product-runtime"; then
  USER_UNIFIED_PRODUCT_RUNTIME=1
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "resident-platform-shutdown-runtime"; then
  USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME=1
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-shutdown-orchestration-runtime"; then
  USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME=1
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "storage-server-clean-shutdown-runtime"; then
  echo "clean-shutdown boot-session closure is kernel-only and has no userspace feature." >&2
  exit 2
fi
if feature_list_contains "$USERSPACE_FEATURES" "storage-server-persistent-health-runtime"; then
  echo "persistent device-health evidence is kernel-only and has no userspace feature." >&2
  exit 2
fi
if feature_list_contains "$USERSPACE_FEATURES" "storage-server-terminal-quarantine-runtime"; then
  USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME=1
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
fi
if feature_list_contains "$USERSPACE_FEATURES" "storage-server-owner-liveness-runtime"; then
  USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME=1
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-fault-policy-runtime"; then
  USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME=1
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-async-recovery-runtime"; then
  USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-repeated-recovery-runtime"; then
  USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-recovery-runtime"; then
  USER_STORAGE_SERVER_RECOVERY_RUNTIME=1
  USER_STORAGE_SERVER_RUNTIME=1
elif feature_list_contains "$USERSPACE_FEATURES" "storage-server-runtime"; then
  USER_STORAGE_SERVER_RUNTIME=1
fi

if [[ "$USER_APP_DATA_ASYNC_RECOVERY_RUNTIME" -eq 1 \
  && "$KERNEL_APP_DATA_ASYNC_RECOVERY_RUNTIME" -ne 1 ]]; then
  echo "userspace AppData async-recovery profile exceeds the kernel AppData profile." >&2
  exit 2
fi
if [[ "$USER_MOBILE_UI_RUNTIME" -ne "$KERNEL_MOBILE_UI_RUNTIME" ]]; then
  echo "mobile-ui-runtime must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_DEX0" -ne "$KERNEL_ANDROIDBOX_DEX0" ]]; then
  echo "androidbox-dex0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_APK_INSTALL0" -ne "$KERNEL_ANDROIDBOX_APK_INSTALL0" ]]; then
  echo "androidbox-apk-install0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_EL0_RUNTIME0" -ne "$KERNEL_ANDROIDBOX_EL0_RUNTIME0" ]]; then
  echo "androidbox-el0-runtime0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_INTERACTIVE0" -ne "$KERNEL_ANDROIDBOX_INTERACTIVE0" ]]; then
  echo "androidbox-interactive0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_PROCESS0" -ne "$KERNEL_ANDROIDBOX_PROCESS0" ]]; then
  echo "androidbox-process0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_RESTART0" -ne "$KERNEL_ANDROIDBOX_RESTART0" ]]; then
  echo "androidbox-restart0 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_SCENE_RPC2" -ne "$KERNEL_ANDROIDBOX_SCENE_RPC2" ]]; then
  echo "androidbox-scene-rpc2 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_MULTIACTION3" -ne "$KERNEL_ANDROIDBOX_MULTIACTION3" ]]; then
  echo "androidbox-multiaction3 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_APK_ENVELOPE4" -ne "$KERNEL_ANDROIDBOX_APK_ENVELOPE4" ]]; then
  echo "androidbox-apk-envelope4 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_RUNTIME_UNINSTALL1" -ne "$KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1" ]]; then
  echo "androidbox-runtime-uninstall1 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_RUNTIME_INSTALL2" -ne "$KERNEL_ANDROIDBOX_RUNTIME_INSTALL2" ]]; then
  echo "androidbox-runtime-install2 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_MANIFEST_CATALOG3" -ne "$KERNEL_ANDROIDBOX_MANIFEST_CATALOG3" ]]; then
  echo "androidbox-manifest-catalog3 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_MULTIPACKAGE4" -ne "$KERNEL_ANDROIDBOX_MULTIPACKAGE4" ]]; then
  echo "androidbox-multipackage4 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_ICON_RESOURCES5" -ne "$KERNEL_ANDROIDBOX_ICON_RESOURCES5" ]]; then
  echo "androidbox-icon-resources5 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_DENSITY_ICONS7" -ne "$KERNEL_ANDROIDBOX_DENSITY_ICONS7" ]]; then
  echo "androidbox-density-icons7 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_DEX_METHODS8" -ne "$KERNEL_ANDROIDBOX_DEX_METHODS8" ]]; then
  echo "androidbox-dex-methods8 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_DEX_INSTANCE9" -ne "$KERNEL_ANDROIDBOX_DEX_INSTANCE9" ]]; then
  echo "androidbox-dex-instance9 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_ACTIVITY_FIELDS10" -ne "$KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10" ]]; then
  echo "androidbox-activity-fields10 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_ACTIVITY_STATE11" -ne "$KERNEL_ANDROIDBOX_ACTIVITY_STATE11" ]]; then
  echo "androidbox-activity-state11 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_STRING_TEXT12" -ne "$KERNEL_ANDROIDBOX_STRING_TEXT12" ]]; then
  echo "androidbox-string-text12 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_STRING_BUILDER13" -ne "$KERNEL_ANDROIDBOX_STRING_BUILDER13" ]]; then
  echo "androidbox-string-builder13 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_ROW14" -ne "$KERNEL_ANDROIDBOX_LAYOUT_ROW14" ]]; then
  echo "androidbox-layout-row14 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_WEIGHT15" -ne "$KERNEL_ANDROIDBOX_LAYOUT_WEIGHT15" ]]; then
  echo "androidbox-layout-weight15 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_SPACING16" -ne "$KERNEL_ANDROIDBOX_LAYOUT_SPACING16" ]]; then
  echo "androidbox-layout-spacing16 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_DIRECTIONAL17" -ne "$KERNEL_ANDROIDBOX_LAYOUT_DIRECTIONAL17" ]]; then
  echo "androidbox-layout-directional17 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_SIZE18" -ne "$KERNEL_ANDROIDBOX_LAYOUT_SIZE18" ]]; then
  echo "androidbox-layout-size18 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_ANDROIDBOX_LAYOUT_MIXED19" -ne "$KERNEL_ANDROIDBOX_LAYOUT_MIXED19" ]]; then
  echo "androidbox-layout-mixed19 must be enabled for both kernel and userspace." >&2
  exit 2
fi
if [[ "$USER_APP_DATA_RUNTIME" -eq 1 \
  && "$KERNEL_APP_DATA_RUNTIME" -ne 1 ]]; then
  echo "userspace AppData profile requires an AppData-enabled kernel." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME" -ne 1 ]]; then
  echo "userspace maintenance-authorization profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME" -ne 1 ]]; then
  echo "userspace maintenance-execution profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME" -ne 1 ]]; then
  echo "userspace maintenance-step profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME" -ne 1 ]]; then
  echo "userspace maintenance-plan profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME" -ne 1 ]]; then
  echo "userspace signed maintenance-plan profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME" -ne 1 ]]; then
  echo "userspace key-rotation profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME" -ne 1 ]]; then
  echo "userspace persistent-rollback profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME" -ne 1 ]]; then
  echo "userspace verified-manifest profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME" -ne 1 ]]; then
  echo "userspace event-supervision profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME" -ne 1 ]]; then
  echo "userspace PSCI-shutdown profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME" -ne 1 ]]; then
  echo "userspace continuous-supervision profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME" -eq 1 \
  && "$KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME" -ne 1 ]]; then
  echo "userspace manifest-supervision profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME" -eq 1 \
  && "$KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME" -ne 1 ]]; then
  echo "userspace resident-platform-shutdown profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME" -ne 1 ]]; then
  echo "userspace shutdown-orchestration profile requires the matching kernel profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME" -ne 1 ]]; then
  echo "userspace terminal-quarantine profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME" -ne 1 ]]; then
  echo "userspace owner-liveness profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_FAULT_POLICY_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME" -ne 1 ]]; then
  echo "userspace fault-policy profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME" -ne 1 ]]; then
  echo "userspace async-recovery profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME" -ne 1 ]]; then
  echo "userspace repeated-recovery profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_RECOVERY_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME" -ne 1 ]]; then
  echo "userspace recovery profile exceeds the kernel storage profile." >&2
  exit 2
fi
if [[ "$USER_STORAGE_SERVER_RUNTIME" -eq 1 \
  && "$KERNEL_STORAGE_SERVER_RUNTIME" -ne 1 ]]; then
  echo "userspace storage profile requires a storage-enabled kernel." >&2
  exit 2
fi

STORAGE_SERVER_RUNTIME=0
RUNTIME_FEATURES_ENABLED=0
if [[ "$USER_MOBILE_UI_RUNTIME" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
fi
if [[ "$KERNEL_ANDROIDBOX_APK_INSTALL0" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-apk-install0")"
fi
if [[ "$KERNEL_ANDROIDBOX_EL0_RUNTIME0" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-el0-runtime0")"
fi
if [[ "$KERNEL_ANDROIDBOX_INTERACTIVE0" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-interactive0")"
fi
if [[ "$KERNEL_ANDROIDBOX_PROCESS0" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-process0")"
fi
if [[ "$KERNEL_ANDROIDBOX_RESTART0" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-restart0")"
fi
if [[ "$KERNEL_ANDROIDBOX_SCENE_RPC2" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-scene-rpc2")"
fi
if [[ "$KERNEL_ANDROIDBOX_MULTIACTION3" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-multiaction3")"
fi
if [[ "$KERNEL_ANDROIDBOX_APK_ENVELOPE4" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-apk-envelope4")"
fi
if [[ "$KERNEL_ANDROIDBOX_RUNTIME_UNINSTALL1" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-runtime-uninstall1")"
fi
if [[ "$KERNEL_ANDROIDBOX_RUNTIME_INSTALL2" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-runtime-install2")"
fi
if [[ "$KERNEL_ANDROIDBOX_MANIFEST_CATALOG3" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-manifest-catalog3")"
fi
if [[ "$KERNEL_ANDROIDBOX_MULTIPACKAGE4" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-multipackage4")"
fi
if [[ "$KERNEL_ANDROIDBOX_ICON_RESOURCES5" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-icon-resources5")"
fi
if [[ "$KERNEL_ANDROIDBOX_DENSITY_ICONS7" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-density-icons7")"
fi
if [[ "$KERNEL_ANDROIDBOX_DEX_METHODS8" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-dex-methods8")"
fi
if [[ "$KERNEL_ANDROIDBOX_DEX_INSTANCE9" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-dex-instance9")"
fi
if [[ "$KERNEL_ANDROIDBOX_ACTIVITY_FIELDS10" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-activity-fields10")"
fi
if [[ "$KERNEL_ANDROIDBOX_ACTIVITY_STATE11" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-activity-state11")"
fi
if [[ "$KERNEL_ANDROIDBOX_STRING_TEXT12" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-string-text12")"
fi
if [[ "$KERNEL_ANDROIDBOX_STRING_BUILDER13" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-string-builder13")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_ROW14" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-row14")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_WEIGHT15" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-weight15")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_SPACING16" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-spacing16")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_DIRECTIONAL17" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-directional17")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_SIZE18" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-size18")"
fi
if [[ "$KERNEL_ANDROIDBOX_LAYOUT_MIXED19" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "androidbox-layout-mixed19")"
fi
if [[ "$KERNEL_APP_DATA_RUNTIME" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "app-data-runtime")"
  if [[ "$KERNEL_APP_DATA_ASYNC_RECOVERY_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "app-data-async-recovery-runtime")"
  fi
fi
if [[ "$KERNEL_STORAGE_SERVER_RUNTIME" -eq 1 ]]; then
  RUNTIME_FEATURES_ENABLED=1
  STORAGE_SERVER_RUNTIME=1
  USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-runtime")"
  if [[ "$KERNEL_STORAGE_SERVER_RECOVERY_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-recovery-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_REPEATED_RECOVERY_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-repeated-recovery-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_ASYNC_RECOVERY_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-async-recovery-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_FAULT_POLICY_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-fault-policy-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_OWNER_LIVENESS_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-owner-liveness-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_TERMINAL_QUARANTINE_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-terminal-quarantine-runtime")"
  fi
  if [[ "$KERNEL_STORAGE_SERVER_SHUTDOWN_ORCHESTRATION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "storage-server-shutdown-orchestration-runtime")"
  fi
  if [[ "$KERNEL_RESIDENT_PLATFORM_SHUTDOWN_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "resident-platform-shutdown-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_LIVENESS_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-liveness-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MULTISERVICE_LIVENESS_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-multiservice-liveness-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_PSCI_SHUTDOWN_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-psci-shutdown-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_CONTINUOUS_SUPERVISION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-continuous-supervision-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MANIFEST_SUPERVISION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-manifest-supervision-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_EVENT_SUPERVISION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-event-supervision-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_VERIFIED_MANIFEST_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-verified-manifest-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_PERSISTENT_ROLLBACK_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-persistent-rollback-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_KEY_ROTATION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-key-rotation-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_AUTHORIZATION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-maintenance-authorization-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_EXECUTION_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-maintenance-execution-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_STEP_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-maintenance-step-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_MAINTENANCE_PLAN_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-maintenance-plan-runtime")"
  fi
  if [[ "$KERNEL_UNIFIED_PRODUCT_SIGNED_MAINTENANCE_PLAN_RUNTIME" -eq 1 ]]; then
    USERSPACE_FEATURES="$(append_feature "$USERSPACE_FEATURES" "unified-product-signed-maintenance-plan-runtime")"
  fi
fi
if [[ "$RUNTIME_FEATURES_ENABLED" -eq 1 ]]; then
  BNDROID_USERSPACE_FEATURES="$USERSPACE_FEATURES" \
    BNDROID_PROFILE="$PROFILE" \
    "$SCRIPT_DIR/build-userspace.sh"
else
  BNDROID_PROFILE="$PROFILE" "$SCRIPT_DIR/build-userspace.sh"
fi
export BNDROID_INIT_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-init"
export BNDROID_SERVICE_MANAGER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-service-manager"
export BNDROID_ECHO_PROVIDER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-echo-provider"
export BNDROID_ECHO_CLIENT_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-echo-client"
export BNDROID_SURFACE_SERVER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-surface-server"
export BNDROID_INPUT_SERVER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-input-server"
export BNDROID_LAUNCHER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-launcher"
export BNDROID_APP_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-app"
if [[ "$KERNEL_ANDROIDBOX_PROCESS0" -eq 1 ]]; then
  export BNDROID_ANDROID_APP_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-android-app"
fi
if [[ "$STORAGE_SERVER_RUNTIME" -eq 1 ]]; then
  export BNDROID_STORAGE_SERVER_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-storage-server"
fi

case "$PROFILE" in
  debug)
    if [[ -n "${BNDROID_KERNEL_FEATURES:-}" ]]; then
      CARGO_TARGET_DIR="$TARGET_ROOT" cargo build --locked --target aarch64-unknown-none -p bndroid-kernel --features "$BNDROID_KERNEL_FEATURES"
    else
      CARGO_TARGET_DIR="$TARGET_ROOT" cargo build --locked --target aarch64-unknown-none -p bndroid-kernel
    fi
    ;;
  release)
    if [[ -n "${BNDROID_KERNEL_FEATURES:-}" ]]; then
      CARGO_TARGET_DIR="$TARGET_ROOT" cargo build --locked --target aarch64-unknown-none -p bndroid-kernel --release --features "$BNDROID_KERNEL_FEATURES"
    else
      CARGO_TARGET_DIR="$TARGET_ROOT" cargo build --locked --target aarch64-unknown-none -p bndroid-kernel --release
    fi
    ;;
  *)
    echo "BNDROID_PROFILE must be 'debug' or 'release'." >&2
    exit 2
    ;;
esac

KERNEL_ELF="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-kernel"
KERNEL_IMAGE="$TARGET_ROOT/aarch64-unknown-none/$PROFILE/bndroid-kernel.img"
RUST_SYSROOT="$(rustc --print sysroot)"
HOST_TRIPLE="$(rustc -vV | sed -n 's/^host: //p')"
RUST_OBJCOPY="$RUST_SYSROOT/lib/rustlib/$HOST_TRIPLE/bin/rust-objcopy"
LLVM_OBJCOPY="$RUST_SYSROOT/lib/rustlib/$HOST_TRIPLE/bin/llvm-objcopy"

if [[ -x "$RUST_OBJCOPY" ]]; then
  OBJCOPY="$RUST_OBJCOPY"
elif [[ -x "$LLVM_OBJCOPY" ]]; then
  OBJCOPY="$LLVM_OBJCOPY"
else
  echo "Neither rust-objcopy nor llvm-objcopy was found under $RUST_SYSROOT." >&2
  echo "Install the llvm-tools-preview component for the active Rust toolchain." >&2
  exit 1
fi

"$OBJCOPY" -O binary "$KERNEL_ELF" "$KERNEL_IMAGE"
echo "Kernel image: $KERNEL_IMAGE"
