#![no_std]

extern crate alloc;
#[cfg(test)]
extern crate std;

pub mod aarch64_paging;
pub mod block;
pub mod bootfs;
pub mod channel;
pub mod compositor;
pub mod event;
#[cfg(feature = "unified-product-event-supervision-runtime")]
pub mod event_supervision_trace;
pub mod fat16;
pub mod fdt;
pub mod frame_clock;
pub mod framebuffer;
pub mod fw_cfg;
pub mod gpt;
pub mod graphics_buffer;
pub mod handles;
pub mod heap;
#[cfg(feature = "input-server-runtime")]
pub mod input_broker;
#[cfg(feature = "input-server-restart-runtime")]
pub mod input_server_restart_trace;
#[cfg(any(
    feature = "input-server-surface-restart-runtime",
    feature = "service-dependency-runtime"
))]
pub mod input_surface_recovery_trace;
pub mod memory;
pub mod object;
pub mod object_wait;
pub mod persist;
#[cfg(feature = "persistent-window-runtime")]
pub mod persistent_window_trace;
#[cfg(feature = "resident-platform-shutdown-runtime")]
pub mod platform_shutdown;
#[cfg(feature = "post-recovery-focus-roundtrip-runtime")]
pub mod post_recovery_focus_roundtrip_trace;
#[cfg(feature = "post-recovery-focus-runtime")]
pub mod post_recovery_focus_trace;
#[cfg(feature = "post-recovery-interaction-runtime")]
pub mod post_recovery_interaction_trace;
#[cfg(feature = "post-recovery-lifecycle-focus-runtime")]
pub mod post_recovery_lifecycle_focus_trace;
pub mod process_wait;
pub mod round_robin;
pub mod service_cycle;
#[cfg(feature = "service-dependency-runtime")]
pub mod service_dependency_trace;
#[cfg(feature = "resident-platform-shutdown-runtime")]
pub mod service_shutdown;
#[cfg(feature = "service-supervisor-runtime")]
pub mod service_supervisor_trace;
#[cfg(feature = "storage-server-shutdown-orchestration-runtime")]
pub mod shutdown;
#[cfg(feature = "soft-keyboard-runtime")]
pub mod soft_keyboard_trace;
#[cfg(feature = "storage-server-runtime")]
pub mod storage_broker;
pub mod storage_owner_liveness;
pub mod storage_recovery_policy;
pub mod storage_terminal_quarantine;
pub mod surface;
pub mod swapchain;
pub mod system_files;
#[cfg(feature = "text-input-runtime")]
pub mod text_input_trace;
pub mod thread_state;
pub mod time;
pub mod timer_queue;
pub mod ui;
#[cfg(feature = "surface-trace-evidence")]
pub mod ui_trace;
#[cfg(feature = "unified-product-runtime")]
pub mod unified_product;
pub mod vfs;
pub mod virtio;
pub mod virtio_input;
pub mod vmo;
#[cfg(feature = "multi-window-runtime")]
pub mod window_trace;
